root_server:
  # The port to connect to root server
  port: 64
  # The url to connect to root server
  url: 'vip.ve.atsign.zone'

# alice atsign details
first_atsign_server:
  first_atsign_name: "@aliceðŸ› "
  # # The port to connect to first atsign server
  first_atsign_port: 25000
  # # The url to connect to first atsign server
  first_atsign_url: vip.ve.atsign.zone

second_atsign_server:
  second_atsign_name: "@bobðŸ› "
  
