# alice atsign details
first_atsign_server:
  # first_atsign_name: "@aliceðŸ› "
  first_atsign_name: "@alice"
  # # The port to connect to first atsign server
  first_atsign_port: 6367
  # # The url to connect to first atsign server
  first_atsign_url: vip.ve.atsign.zone

second_atsign_server:
  second_atsign_name: "@bob"
  
