# The @Protocol root server configuration
root_server:
  # The port to connect to root server
  port: 64
  # The url to connect to root server
  url: 'root.atsign.wtf'

# cicd atsign details
first_atsign_server:
  first_atsign_name: '@cicd5'
  # # The port to connect to first atsign server
  first_atsign_port: 6466
  # # The url to connect to first atsign server
  first_atsign_url: cicd5.atsign.wtf

second_atsign_server:
  second_atsign_name: '@cicd6'
  # # The port to connect to second atsign server
  second_atsign_port: 6466
  # # The url to connect to second atsign server
  second_atsign_url: cicd6.atsign.wtf