name: at_secondary
description: Implementation of secondary server.
version: 3.0.36
repository: https://github.com/atsign-foundation/at_server
homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  args: 2.4.2
  uuid: 3.0.7
  convert: 3.1.1
  cron: 0.5.1
  crypto: 3.0.3
  crypton: 2.2.0
  collection: 1.18.0
  basic_utils: 5.6.1
  ecdsa: 0.0.4
  encrypt: 5.0.3
  at_commons: 3.0.55
  at_utils: 3.0.15
  at_chops: 1.0.4
  at_lookup: 3.0.40
  at_server_spec: 3.0.15
  at_persistence_spec: 2.0.14
  at_persistence_secondary_server: 3.0.57
  intl: ^0.18.1
  json_annotation: ^4.8.0
  version: 3.0.2
  meta: 1.10.0
  mutex: 3.0.1
  yaml: 3.1.2
  logging: 1.2.0

dependency_overrides:
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_commons
      ref: expire_otp_changes



dev_dependencies:
  test: ^1.24.4
  coverage: ^1.6.1
  lints: ^2.1.1
  mocktail: ^0.3.0
