name: at_secondary
description: Implementation of secondary server.
version: 2.0.1-NULLSAFETY
repository: https://github.com/atsign-foundation/at_server
homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  uuid: ^3.0.4
  convert: ^3.0.0
  crypto: ^3.0.1
  crypton: ^2.0.1
  collection: ^1.15.0
  basic_utils: ^3.0.2
  at_persistence_secondary_server: ^1.0.1+8
  at_lookup: ^1.0.0+8
  at_server_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_server_spec
      ref: trunk
      version: ^2.0.0

dependency_overrides:
  at_persistence_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_persistence/at_persistence_spec
      ref: sdk_refactoring
      version: ^2.0.0
  at_persistence_secondary_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_secondary/at_persistence_secondary_server
      ref: sdk_refactoring
      version: ^2.0.0
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: sdk_refactoring
      version: ^2.0.1
  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: sdk_refactoring
      version: ^2.0.0
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: stream_resume
      version: ^2.0.2
  at_server_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_server_spec
      ref: sdk_refactoring
      version: ^2.0.1

dev_dependencies:
  test: ^1.17.3
  #  test_coverage: ^0.5.0
  mockito: ^5.0.7
