name: at_secondary
description: Implementation of secondary server.
version: 1.0.0+DEV
repository: https://github.com/atsign-foundation/at_server
homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  uuid: ^2.0.2
  convert: ^2.1.1
  crypto: ^3.0.0
  crypton: ^1.1.0
  collection: ^1.14.13
  at_persistence_secondary_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_secondary/at_persistence_secondary_server
      ref: package_upgrade
      version: ^1.0.1+4

  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: package_upgrade
      ref: dev_env
      version: ^1.0.0+4

  at_server_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_server_spec
      ref: package_upgrade
      version: ^1.0.0

#dependency_overrides:
#  at_persistence_secondary_server:
#    path: ../at_persistence_secondary_server
#  at_server_spec:
#    path: ../../at_server_spec
#  at_persistence_spec:
#    path: ../../at_persistence/at_persistence_spec
#  at_utils:
#    path: ../../../at_tools/at_utils
#  at_commons:
#    path: ../../../at_tools/at_commons
#  at_lookup:
#    path: ../../../at_libraries/at_lookup

dev_dependencies:
  test: ^1.6.0
  test_coverage: ^0.4.1
  mockito: ^4.1.1
  basic_utils: ^2.2.2
