name: at_secondary
description: Implementation of secondary server.
version: 3.0.13
repository: https://github.com/atsign-foundation/at_server
homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  uuid: ^3.0.4
  convert: ^3.0.0
  crypto: ^3.0.1
  crypton: ^2.0.1
  collection: ^1.15.0
  basic_utils: ^3.0.2
  at_persistence_secondary_server: ^3.0.17
  at_lookup: ^3.0.11
  at_server_spec: ^3.0.1

dependency_overrides:
#  at_commons:
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_commons
#       ref: trunk
   at_persistence_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_persistence/at_persistence_spec
      ref: compaction_stats_patch1
#   at_utils:
#     git:
#       url: https://github.com/atsign-foundation/at_tools.git
#       path: at_utils
#        ref: reset_ttl_ttb
   at_persistence_secondary_server:
     git:
       url: https://github.com/atsign-foundation/at_server.git
       path: at_secondary/at_persistence_secondary_server
       ref: compaction_stats_patch2
#  at_server_spec:
#    git:
#      url: https://github.com/atsign-foundation/at_server.git
#      path: at_server_spec
#      ref: trunk

dev_dependencies:
  test: ^1.17.3
  coverage: ^1.0.3
  mockito: ^5.0.7
  lints: ^1.0.1
