name: at_server_spec
description: Specification for root and secondary server
version: 1.0.0
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_server_spec/index.html

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: master
      version: ^1.0.0
#dependency_overrides:
#  at_commons:
#    path: ../at_commons
dev_dependencies:
  pedantic: ^1.8.0