name: at_root_server
description: Root server implementation.
version: 2.1.0
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
publish_to: none

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  args: 2.4.2
  uuid: 3.0.6
  yaml: 3.1.2
  at_commons: 3.0.56
  at_utils: 3.0.15
  at_server_spec: 3.0.15
  at_persistence_root_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: packages/at_persistence_root_server
      ref: trunk
      version: ^2.0.5

dev_dependencies:
  # Adding test_cov for generating the test coverage.
  test_cov: ^1.0.1
  lints: ^2.1.1
  test: ^1.24.6
  coverage: ^1.6.3
