name: at_persistence_root_server
description: Implementation for root server related persistence.
version: 1.0.0
repository: https://github.com/atsign-foundation/at_server
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_persistence_root_server/index.html

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  redis: ^1.2.0
  at_persistence_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_persistence/at_persistence_spec
      ref: package_upgrade
      version: ^1.0.1+3

  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: package_upgrade
      version: ^1.0.1+4

#dependency_overrides:
#  at_persistence_spec:
#    path: ../../../at_server/at_persistence/at_persistence_spec
#  at_utils:
#    path: ../../../at_tools/at_utils

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.14.2
  mockito: ^4.1.1
  test_coverage: ^0.4.1
