name: at_functional_test
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  at_demo_data:
    git:
      url: https://github.com/atsign-foundation/at_demos.git
      path: at_demo_data
      ref: master
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: trunk
      version: ^1.1.0

#dependency_overrides:
#  at_lookup:
#    path: ../../at_libraries/at_lookup
#  at_utils:
#    path: ../../at_tools/at_utils

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
