# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: at_root

on:
  pull_request:
    branches:
      - master
      - trunk
      - dev_env

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies in at_persistence_root_server
        working-directory: at_root/at_persistence_root_server
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source in at_persistence_root_server
        working-directory: at_root/at_persistence_root_server
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests in at_persistence_root_server
        working-directory: at_root/at_persistence_root_server
        run: dart test --concurrency=1

      - name: Install dependencies in at_root_server
        working-directory: at_root/at_root_server
        run: dart pub get

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source in at_root_server
        working-directory: at_root/at_root_server
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests in at_root_server
        working-directory: at_root/at_root_server
        run: dart test --concurrency=1